# Generated by Django 6.0 on 2025-12-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M4ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=100, verbose_name='품명')),
                ('request_no', models.CharField(max_length=20, unique=True, verbose_name='관리번호')),
                ('m4_type', models.CharField(choices=[('MAN', '작업자(Man)'), ('MACHINE', '설비(Machine)'), ('MATERIAL', '재료(Material)'), ('METHOD', '공법(Method)')], max_length=10, verbose_name='변경구분')),
                ('status', models.CharField(choices=[('PENDING', '승인대기'), ('APPROVED', '승인완료'), ('REJECTED', '반려')], default='PENDING', max_length=10, verbose_name='진행상태')),
                ('has_isir', models.BooleanField(default=False, verbose_name='ISIR')),
                ('has_process_flow', models.BooleanField(default=False, verbose_name='공정흐름도')),
                ('has_control_plan', models.BooleanField(default=False, verbose_name='관리계획서')),
                ('has_fmea', models.BooleanField(default=False, verbose_name='FMEA')),
                ('has_work_standard', models.BooleanField(default=False, verbose_name='작업표준서')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='완료목표일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
