# Generated by Django 6.0 on 2025-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0002_m4request_delete_m4changerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='m4request',
            name='factory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='공장'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='차종'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='제품'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='변경사유'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='m4_type',
            field=models.CharField(choices=[('MAN', '작업자(Man)'), ('MACHINE', '설비(Machine)'), ('MATERIAL', 'Material (재료)'), ('METHOD', 'Method (방법)')], max_length=10, verbose_name='변경구분'),
        ),
    ]
