# Generated by Django 6.0 on 2025-12-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0003_m4request_factory_m4request_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m4request',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='m4request',
            name='affected_features',
            field=models.TextField(blank=True, null=True, verbose_name='영향받는 특성치'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='content_after',
            field=models.TextField(blank=True, null=True, verbose_name='변경후'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='content_before',
            field=models.TextField(blank=True, null=True, verbose_name='변경전'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step1',
            field=models.DateField(blank=True, null=True, verbose_name='1.공정준비'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step2',
            field=models.DateField(blank=True, null=True, verbose_name='2.표준류 정비'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step3',
            field=models.DateField(blank=True, null=True, verbose_name='3.공정안정화'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step4',
            field=models.DateField(blank=True, null=True, verbose_name='4.초품검사'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step5',
            field=models.DateField(blank=True, null=True, verbose_name='5.초품 SAMPLE 제출'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step6',
            field=models.DateField(blank=True, null=True, verbose_name='6.초품승인 완료'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step7',
            field=models.DateField(blank=True, null=True, verbose_name='7.양산개시'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='plan_step8',
            field=models.DateField(blank=True, null=True, verbose_name='8.변경초품 납품'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='quality_rank',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='품질RANK'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='m4_type',
            field=models.CharField(choices=[('MAN', '작업자(Man)'), ('MACHINE', '설비(Machine)'), ('MATERIAL', '재료(Material)'), ('METHOD', '공법(Method)')], max_length=10, verbose_name='변경구분'),
        ),
    ]
