# Generated by Django 6.0 on 2025-12-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0004_remove_m4request_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m4request',
            name='photo_after',
            field=models.FileField(blank=True, null=True, upload_to='qms/m4/', verbose_name='변경후 사진'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='photo_before',
            field=models.FileField(blank=True, null=True, upload_to='qms/m4/', verbose_name='변경전 사진'),
        ),
    ]
