# Generated by Django 6.0 on 2025-12-26 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0005_m4request_photo_after_m4request_photo_before'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M4Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='검토부서')),
                ('content', models.TextField(verbose_name='검토내용')),
                ('received_at', models.DateField(auto_now_add=True, verbose_name='접수일')),
                ('sent_at', models.DateField(auto_now=True, verbose_name='발송일')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='qms.m4request')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
        ),
    ]
