# Generated by Django 6.0 on 2025-12-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0006_m4review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='m4review',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='검토자성함'),
        ),
        migrations.AlterField(
            model_name='m4review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='기록자'),
        ),
    ]
