# Generated by Django 6.0 on 2025-12-26 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0007_m4review_reviewer_name_alter_m4review_reviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='m4request',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='approver_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_approver_set', to=settings.AUTH_USER_MODEL, verbose_name='최종승인자'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='승인여부'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='검토여부'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토일시'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='reviewer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_reviewer_set', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', '검토대기'), ('PENDING_APPROVE', '승인대기'), ('APPROVED', '승인완료'), ('REJECTED', '반려')], default='PENDING_REVIEW', max_length=20, verbose_name='진행상태'),
        ),
    ]
