# Generated by Django 6.0 on 2025-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0008_m4request_approved_at_m4request_approver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m4request',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='반려사유'),
        ),
    ]
