# Generated by Django 6.0 on 2025-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0009_m4request_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m4request',
            name='reject_reason',
        ),
        migrations.AddField(
            model_name='m4request',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='기안여부'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='기안일시'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('PENDING_REVIEW', '검토대기'), ('PENDING_APPROVE', '승인대기'), ('APPROVED', '승인완료'), ('REJECTED', '반려')], default='DRAFT', max_length=20, verbose_name='진행상태'),
        ),
    ]
