# Generated by Django 6.0 on 2025-12-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0010_remove_m4request_reject_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M4ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='수정필드')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='이전내용')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='변경내용')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='수정일시')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='qms.m4request', verbose_name='관련요청')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
