# Generated by Django 6.0 on 2025-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0011_m4changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='m4review',
            name='request_content',
            field=models.TextField(blank=True, null=True, verbose_name='품질팀 요청사항'),
        ),
        migrations.AlterField(
            model_name='m4review',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='검토답변'),
        ),
        migrations.AlterField(
            model_name='m4review',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='접수일(회신)'),
        ),
        migrations.AlterField(
            model_name='m4review',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='발송일(요청)'),
        ),
    ]
