# Generated by Django 6.0 on 2025-12-27 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_organization_and_userprofile_fields'),
        ('qms', '0015_formal4m_full_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='m4request',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_approver_set', to=settings.AUTH_USER_MODEL, verbose_name='최종승인자'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_reviewer_set', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='vendor_org',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_requests', to='orders.organization', verbose_name='협력사(대상)'),
        ),
    ]
