# Generated by ChatGPT on 2025-12-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0017_m4request_reject_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="m4request",
            name="reviewer_user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="m4_reviewer2_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="검토2",
            ),
        ),
        migrations.AddField(
            model_name="m4request",
            name="is_reviewed2",
            field=models.BooleanField(default=False, verbose_name="검토2여부"),
        ),
        migrations.AddField(
            model_name="m4request",
            name="reviewed2_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="검토2일시"),
        ),
    ]
