# Generated by ChatGPT on 2025-12-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0018_m4_second_review_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "작성중"),
                    ("PENDING_REVIEW", "검토대기"),
                    ("PENDING_REVIEW2", "검토2대기"),
                    ("PENDING_APPROVE", "승인대기"),
                    ("APPROVED", "승인완료"),
                    ("REJECTED", "반려"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="결재상태",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_reviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formal4m_reviewer1_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="검토1",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_reviewer_user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formal4m_reviewer2_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="검토2",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_approver_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formal4m_approver_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최종승인자",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_is_submitted",
            field=models.BooleanField(default=False, verbose_name="상신여부"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="상신일시"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_is_reviewed",
            field=models.BooleanField(default=False, verbose_name="검토1여부"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="검토1일시"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_is_reviewed2",
            field=models.BooleanField(default=False, verbose_name="검토2여부"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_reviewed2_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="검토2일시"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_is_approved",
            field=models.BooleanField(default=False, verbose_name="최종승인여부"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="최종승인일시"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="approval_reject_reason",
            field=models.TextField(blank=True, null=True, verbose_name="반려사유"),
        ),
    ]
