# Generated by Django 6.0 on 2025-12-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0019_formal4m_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='formal4mrequest',
            name='validity_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='유효성평가 시작일'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('PENDING_REVIEW', '검토대기'), ('PENDING_REVIEW2', '검토2대기'), ('PENDING_APPROVE', '승인대기'), ('APPROVED', '승인완료'), ('REJECTED', '반려')], default='DRAFT', max_length=20, verbose_name='진행상태'),
        ),
    ]
