# Generated by ChatGPT on 2026-01-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0020_formal4mrequest_validity_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="m4request",
            name="change_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "품질시스템(A)"),
                    ("B", "설계변경(B)"),
                    ("C", "공정변경(C)"),
                    ("D", "구매변경(D)"),
                ],
                max_length=1,
                null=True,
                verbose_name="변경구분(A/B/C/D)",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="change_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "품질시스템(A)"),
                    ("B", "설계변경(B)"),
                    ("C", "공정변경(C)"),
                    ("D", "구매변경(D)"),
                ],
                max_length=1,
                null=True,
                verbose_name="변경구분(A/B/C/D)",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="customer_notice_required",
            field=models.BooleanField(default=False, verbose_name="고객변경신고 필요"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="customer_notice_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formal4m_customer_notice_decisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="고객변경신고 필요여부 결정자",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="customer_notice_decided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="결정일시"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="customer_notice_reason",
            field=models.TextField(blank=True, null=True, verbose_name="결정사유/근거"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="validity_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONGOING", "진행중"),
                    ("PASS", "적합"),
                    ("FAIL", "부적합"),
                ],
                max_length=10,
                null=True,
                verbose_name="유효성평가 결과",
            ),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="validity_closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="유효성평가 완료일시"),
        ),
        migrations.AddField(
            model_name="formal4mrequest",
            name="validity_evidence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="qms/formal4m/validity/",
                verbose_name="유효성평가 증빙파일",
            ),
        ),
    ]
