# Generated by Django 6.0 on 2026-01-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0021_change_management_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formal4mstagerecord',
            name='stage',
            field=models.CharField(choices=[('ISIR', 'ISIR제출'), ('OEM_APPROVAL', 'OEM승인'), ('INTERNAL_APPLY', '사내적용'), ('CUSTOMER_APPLY', '고객적용'), ('MASS_PRODUCTION_REVIEW', '양산이행회의(Go/No-Go)'), ('CUSTOMER_NOTICE', '고객변경신고/통보'), ('OTHER', '기타')], max_length=30, verbose_name='단계'),
        ),
    ]
