# Generated by Django 6.0 on 2026-01-12 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('qms', '0022_alter_formal4mstagerecord_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '검사대기'), ('APPROVED', '합격(입고승인)'), ('REJECTED', '불합격(반품/폐기)')], default='PENDING', max_length=20, verbose_name='검사상태')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='검사일시')),
                ('check_report', models.BooleanField(default=False, verbose_name='성적서 확인')),
                ('check_visual', models.BooleanField(default=False, verbose_name='외관 검사')),
                ('check_dimension', models.BooleanField(default=False, verbose_name='치수/기능 검사')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='검사 의견')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='qms/inspection/', verbose_name='검사 성적서/사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('inbound_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='material.materialtransaction', verbose_name='관련 입고이력')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검사자')),
            ],
            options={
                'verbose_name': '수입검사',
                'verbose_name_plural': '수입검사 관리',
            },
        ),
    ]
