# Generated by Django 6.0 on 2026-01-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0023_importinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='importinspection',
            name='lot_no',
            field=models.DateField(blank=True, null=True, verbose_name='LOT 번호(생산일)'),
        ),
    ]
