# Generated by Django 6.0 on 2026-01-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0024_add_lot_to_import_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='importinspection',
            name='qty_bad',
            field=models.IntegerField(default=0, verbose_name='불량 수량'),
        ),
        migrations.AddField(
            model_name='importinspection',
            name='qty_good',
            field=models.IntegerField(default=0, verbose_name='양품 수량'),
        ),
    ]
