# Generated by Django 6.0 on 2026-01-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0025_importinspection_qty_bad_importinspection_qty_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='importinspection',
            name='target_warehouse_code',
            field=models.CharField(default='2000', max_length=20, verbose_name='목표 창고'),
        ),
    ]
