# Generated by Django 6.0 on 2026-01-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_change_request_v2'),
        ('qms', '0026_add_target_warehouse_to_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=30, unique=True, verbose_name='관리번호')),
                ('phase', models.CharField(choices=[('DRAFT', '작성중'), ('REVIEW', '검토중'), ('APPROVED', '승인완료'), ('FORMAL', '정식진행'), ('VALIDATION', '유효성평가'), ('CLOSED', '완료'), ('REJECTED', '반려'), ('CANCELED', '취소')], default='DRAFT', max_length=15, verbose_name='진행단계')),
                ('change_type', models.CharField(choices=[('MAN', '작업자(Man)'), ('MACHINE', '설비(Machine)'), ('MATERIAL', '자재(Material)'), ('METHOD', '공법(Method)')], max_length=10, verbose_name='4M유형')),
                ('change_grade', models.CharField(blank=True, choices=[('A', 'A등급 - 품질시스템'), ('B', 'B등급 - 설계변경'), ('C', 'C등급 - 공정변경'), ('D', 'D등급 - 구매변경')], max_length=1, null=True, verbose_name='변경등급')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=100, verbose_name='품명')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='차종/모델')),
                ('reason', models.TextField(verbose_name='변경사유')),
                ('content_before', models.TextField(verbose_name='변경 전 내용')),
                ('content_after', models.TextField(verbose_name='변경 후 내용')),
                ('affected_items', models.TextField(blank=True, verbose_name='영향받는 특성/항목')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='목표완료일')),
                ('formal_start_date', models.DateField(blank=True, null=True, verbose_name='정식 시작일')),
                ('validation_due_date', models.DateField(blank=True, null=True, verbose_name='유효성평가 기한')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='완료일')),
                ('customer_notice_required', models.BooleanField(default=False, verbose_name='고객신고 필요')),
                ('customer_notice_date', models.DateField(blank=True, null=True, verbose_name='고객신고일')),
                ('customer_approval_date', models.DateField(blank=True, null=True, verbose_name='고객승인일')),
                ('validity_result', models.CharField(choices=[('PENDING', '대기'), ('PASS', '합격'), ('FAIL', '불합격')], default='PENDING', max_length=10, verbose_name='유효성결과')),
                ('validity_remark', models.TextField(blank=True, verbose_name='유효성평가 비고')),
                ('reject_reason', models.TextField(blank=True, verbose_name='반려사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
                ('vendor', models.ForeignKey(limit_choices_to={'org_type': 'VENDOR'}, on_delete=django.db.models.deletion.PROTECT, to='orders.organization', verbose_name='협력사')),
            ],
            options={
                'verbose_name': '4M변경신청',
                'verbose_name_plural': '4M변경신청 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SUBMIT', '상신'), ('APPROVE', '승인'), ('REJECT', '반려'), ('PHASE_CHANGE', '단계전환'), ('VENDOR_REQUEST', '협력사요청'), ('VENDOR_RESPONSE', '협력사회신'), ('DOC_UPLOAD', '서류업로드'), ('DOC_REVIEW', '서류검토')], max_length=20, verbose_name='액션')),
                ('description', models.TextField(verbose_name='상세내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='변경필드')),
                ('old_value', models.TextField(blank=True, verbose_name='변경전')),
                ('new_value', models.TextField(blank=True, verbose_name='변경후')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수행자')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='qms.changerequest')),
            ],
            options={
                'verbose_name': '변경이력',
                'verbose_name_plural': '변경이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, verbose_name='서류명')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수여부')),
                ('file', models.FileField(blank=True, null=True, upload_to='qms/change_docs/', verbose_name='파일')),
                ('review_status', models.CharField(choices=[('PENDING', '검토대기'), ('OK', '적합'), ('REJECT', '부적합')], default='PENDING', max_length=10, verbose_name='검토상태')),
                ('review_comment', models.TextField(blank=True, verbose_name='검토의견')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='업로드일시')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qms.changerequest')),
            ],
            options={
                'verbose_name': '제출서류',
                'verbose_name_plural': '제출서류',
                'ordering': ['change_request', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=100, verbose_name='요청제목')),
                ('request_content', models.TextField(verbose_name='요청내용')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('status', models.CharField(choices=[('REQUESTED', '요청됨'), ('RESPONDED', '회신완료')], default='REQUESTED', max_length=15, verbose_name='상태')),
                ('response_content', models.TextField(blank=True, verbose_name='회신내용')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='회신일시')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_responses', to='qms.changerequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_responses_sent', to=settings.AUTH_USER_MODEL, verbose_name='회신자')),
            ],
            options={
                'verbose_name': '협력사회신',
                'verbose_name_plural': '협력사회신',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorResponseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qms/vendor_response/', verbose_name='파일')),
                ('file_name', models.CharField(max_length=200, verbose_name='파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='qms.vendorresponse')),
            ],
            options={
                'verbose_name': '회신첨부파일',
                'verbose_name_plural': '회신첨부파일',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(default=1, verbose_name='순서')),
                ('step_type', models.CharField(choices=[('REVIEW', '검토'), ('APPROVE', '승인')], max_length=10, verbose_name='단계유형')),
                ('step_name', models.CharField(max_length=30, verbose_name='단계명')),
                ('status', models.CharField(choices=[('WAITING', '대기'), ('PENDING', '결재대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='WAITING', max_length=10, verbose_name='상태')),
                ('comment', models.TextField(blank=True, verbose_name='의견')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='qms.changerequest')),
            ],
            options={
                'verbose_name': '결재단계',
                'verbose_name_plural': '결재단계',
                'ordering': ['change_request', 'step_order'],
                'unique_together': {('change_request', 'step_order')},
            },
        ),
    ]
