# Generated by Django 6.0 on 2026-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0027_change_request_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='factory',
            field=models.CharField(blank=True, default='2공장', max_length=20, verbose_name='공장'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='사외'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='사내'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='품목군'),
        ),
    ]
