# Generated by Django 6.0 on 2026-01-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0028_change_request_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='m4request',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='사외'),
        ),
        migrations.AddField(
            model_name='m4request',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='사내'),
        ),
        migrations.AlterField(
            model_name='m4request',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='품목군'),
        ),
    ]
