# Generated by Django 6.0 on 2026-01-24 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_change_request_v2'),
        ('qms', '0030_qms_extended_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorclaim',
            name='claim_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='클레임 청구 금액 (원)', max_digits=12, null=True, verbose_name='클레임금액'),
        ),
        migrations.AddField(
            model_name='vendorclaim',
            name='settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='정산일'),
        ),
        migrations.AddField(
            model_name='vendorclaim',
            name='settlement_remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='정산비고'),
        ),
        migrations.AddField(
            model_name='vendorclaim',
            name='settlement_status',
            field=models.CharField(choices=[('NOT_SETTLED', '미정산'), ('IN_PROGRESS', '정산중'), ('SETTLED', '정산완료')], default='NOT_SETTLED', max_length=15, verbose_name='정산상태'),
        ),
        migrations.CreateModel(
            name='ISIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isir_no', models.CharField(max_length=30, unique=True, verbose_name='ISIR번호')),
                ('isir_type', models.CharField(choices=[('NEW_PART', '신규부품'), ('NEW_VENDOR', '신규협력사'), ('DESIGN_CHANGE', '설계변경'), ('PROCESS_CHANGE', '공정변경'), ('MATERIAL_CHANGE', '재질변경'), ('RELOCATION', '이전'), ('REQUALIFICATION', '재인증')], max_length=20, verbose_name='유형')),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('SUBMITTED', '제출'), ('REVIEWING', '검토중'), ('APPROVED', '승인'), ('CONDITIONAL', '조건부승인'), ('REJECTED', '반려')], default='DRAFT', max_length=15, verbose_name='상태')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=100, verbose_name='품명')),
                ('part_rev', models.CharField(blank=True, max_length=20, verbose_name='도면REV')),
                ('drawing_no', models.CharField(blank=True, max_length=50, verbose_name='도면번호')),
                ('sample_qty', models.IntegerField(default=5, verbose_name='샘플수량')),
                ('sample_lot', models.CharField(blank=True, max_length=50, verbose_name='샘플LOT')),
                ('sample_received_date', models.DateField(blank=True, null=True, verbose_name='샘플입고일')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='검사일')),
                ('dimension_result', models.CharField(blank=True, choices=[('PASS', '합격'), ('FAIL', '불합격'), ('NA', 'N/A')], max_length=10, verbose_name='치수검사')),
                ('appearance_result', models.CharField(blank=True, choices=[('PASS', '합격'), ('FAIL', '불합격'), ('NA', 'N/A')], max_length=10, verbose_name='외관검사')),
                ('function_result', models.CharField(blank=True, choices=[('PASS', '합격'), ('FAIL', '불합격'), ('NA', 'N/A')], max_length=10, verbose_name='기능검사')),
                ('material_result', models.CharField(blank=True, choices=[('PASS', '합격'), ('FAIL', '불합격'), ('NA', 'N/A')], max_length=10, verbose_name='재질검사')),
                ('overall_result', models.CharField(blank=True, choices=[('PASS', '합격'), ('FAIL', '불합격'), ('CONDITIONAL', '조건부')], max_length=15, verbose_name='종합판정')),
                ('inspection_detail', models.TextField(blank=True, verbose_name='검사 상세')),
                ('issue_found', models.TextField(blank=True, verbose_name='발견 문제점')),
                ('corrective_action', models.TextField(blank=True, verbose_name='시정조치 요구사항')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='qms/isir/reports/', verbose_name='검사성적서')),
                ('photo1', models.FileField(blank=True, null=True, upload_to='qms/isir/photos/', verbose_name='사진1')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='qms/isir/photos/', verbose_name='사진2')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='승인일')),
                ('approval_remark', models.TextField(blank=True, verbose_name='승인비고')),
                ('condition_detail', models.TextField(blank=True, verbose_name='조건부 승인 조건')),
                ('condition_due_date', models.DateField(blank=True, null=True, verbose_name='조건 이행기한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isir_approved', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isir_created', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isir_inspected', to=settings.AUTH_USER_MODEL, verbose_name='검사자')),
                ('vendor', models.ForeignKey(limit_choices_to={'org_type': 'VENDOR'}, on_delete=django.db.models.deletion.PROTECT, to='orders.organization', verbose_name='협력사')),
            ],
            options={
                'verbose_name': '초도품검사',
                'verbose_name_plural': 'ISIR (초도품검사)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ISIRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(verbose_name='항목번호')),
                ('item_name', models.CharField(max_length=100, verbose_name='검사항목')),
                ('specification', models.CharField(max_length=100, verbose_name='규격')),
                ('tolerance', models.CharField(blank=True, max_length=50, verbose_name='공차')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='단위')),
                ('measured_1', models.CharField(blank=True, max_length=50, verbose_name='측정값1')),
                ('measured_2', models.CharField(blank=True, max_length=50, verbose_name='측정값2')),
                ('measured_3', models.CharField(blank=True, max_length=50, verbose_name='측정값3')),
                ('measured_4', models.CharField(blank=True, max_length=50, verbose_name='측정값4')),
                ('measured_5', models.CharField(blank=True, max_length=50, verbose_name='측정값5')),
                ('result', models.CharField(choices=[('PASS', '합격'), ('FAIL', '불합격')], default='PASS', max_length=10, verbose_name='판정')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('isir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qms.isir', verbose_name='ISIR')),
            ],
            options={
                'verbose_name': 'ISIR 검사항목',
                'verbose_name_plural': 'ISIR 검사항목',
                'ordering': ['isir', 'item_no'],
            },
        ),
    ]
