# Generated by Django 6.0 on 2026-01-24 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0032_add_voc_gauge_qdoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='isir',
            name='cpk_characteristic',
            field=models.CharField(blank=True, help_text='Cpk 산출에 사용된 주요 특성', max_length=100, verbose_name='Cpk 측정특성'),
        ),
        migrations.AddField(
            model_name='isir',
            name='cpk_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='공정능력지수 (≥1.33 권장)', max_digits=5, null=True, verbose_name='Cpk'),
        ),
        migrations.AddField(
            model_name='isir',
            name='lsl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='LSL (하한규격)'),
        ),
        migrations.AddField(
            model_name='isir',
            name='msa_grr_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='≤10%: 적합, 10~30%: 조건부, >30%: 부적합', max_digits=5, null=True, verbose_name='Gage R&R (%)'),
        ),
        migrations.AddField(
            model_name='isir',
            name='msa_ndc',
            field=models.IntegerField(blank=True, help_text='Number of Distinct Categories (≥5 권장)', null=True, verbose_name='NDC (구별범주수)'),
        ),
        migrations.AddField(
            model_name='isir',
            name='msa_result',
            field=models.CharField(blank=True, choices=[('PASS', '적합'), ('CONDITIONAL', '조건부'), ('FAIL', '부적합')], max_length=15, verbose_name='MSA 판정'),
        ),
        migrations.AddField(
            model_name='isir',
            name='ppk_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='공정성능지수 (≥1.67 권장)', max_digits=5, null=True, verbose_name='Ppk'),
        ),
        migrations.AddField(
            model_name='isir',
            name='process_mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='공정평균'),
        ),
        migrations.AddField(
            model_name='isir',
            name='process_std',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='표준편차'),
        ),
        migrations.AddField(
            model_name='isir',
            name='spc_sample_size',
            field=models.IntegerField(blank=True, help_text='공정능력 산출 샘플 수 (최소 30개 권장)', null=True, verbose_name='SPC 샘플수'),
        ),
        migrations.AddField(
            model_name='isir',
            name='usl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='USL (상한규격)'),
        ),
        migrations.CreateModel(
            name='ISIRAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('DRAWING', '도면'), ('REPORT', '검사성적서'), ('CERTIFICATE', '인증서/시험성적서'), ('SPC', 'SPC 데이터'), ('MSA', 'MSA/Gage R&R'), ('FMEA', 'FMEA'), ('CONTROL_PLAN', 'Control Plan'), ('FLOW_CHART', '공정흐름도'), ('PHOTO', '사진'), ('OTHER', '기타')], max_length=20, verbose_name='파일유형')),
                ('file', models.FileField(upload_to='qms/isir/attachments/', verbose_name='파일')),
                ('file_name', models.CharField(max_length=200, verbose_name='파일명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('isir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='qms.isir', verbose_name='ISIR')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': 'ISIR 첨부파일',
                'verbose_name_plural': 'ISIR 첨부파일',
                'ordering': ['file_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ISIRChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem_01_design_records', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='설계기록')),
                ('elem_02_ecn', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='설계변경문서')),
                ('elem_03_customer_approval', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='고객기술승인')),
                ('elem_04_dfmea', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='설계FMEA')),
                ('elem_05_process_flow', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='공정흐름도')),
                ('elem_06_pfmea', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='공정FMEA')),
                ('elem_07_control_plan', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='관리계획서')),
                ('elem_08_msa', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='MSA')),
                ('elem_09_dimensional', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='치수검사결과')),
                ('elem_10_material_test', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='재료시험')),
                ('elem_11_initial_process', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='초기공정연구')),
                ('elem_12_lab_doc', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='공인시험성적')),
                ('elem_13_aar', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='외관승인')),
                ('elem_14_sample', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='샘플제품')),
                ('elem_15_master_sample', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='마스터샘플')),
                ('elem_16_checking_aids', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='검사보조기구')),
                ('elem_17_csr', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='고객요구사항')),
                ('elem_18_psw', models.CharField(choices=[('SUBMITTED', '제출'), ('NOT_REQUIRED', '해당없음'), ('PENDING', '보류'), ('NOT_SUBMITTED', '미제출')], default='NOT_SUBMITTED', max_length=15, verbose_name='PSW')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('isir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='qms.isir', verbose_name='ISIR')),
            ],
            options={
                'verbose_name': 'ISIR 체크리스트',
                'verbose_name_plural': 'ISIR 체크리스트',
            },
        ),
    ]
