# Generated by Django 6.0 on 2026-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0033_isir_cpk_characteristic_isir_cpk_value_isir_lsl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m4request',
            name='factory',
            field=models.CharField(blank=True, choices=[('1공장', '1공장'), ('2공장', '2공장'), ('3공장', '3공장'), ('4공장', '4공장'), ('외주', '외주')], max_length=50, null=True, verbose_name='공장'),
        ),
    ]
