# Generated by Django 6.0 on 2026-04-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='소속')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='직함')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('recipient_type', models.CharField(choices=[('INTERNAL', '내부 직원'), ('VENDOR', '협력사')], default='INTERNAL', max_length=10, verbose_name='구분')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '알림 수신자',
                'verbose_name_plural': '알림 수신자',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_CREATED', '발주 등록'), ('ORDER_APPROVED', '발주 승인'), ('INSPECTION_CREATED', '수입검사 등록'), ('INSPECTION_PASSED', '수입검사 합격'), ('INSPECTION_FAILED', '수입검사 불합격'), ('M4_CREATED', '4M 변경 등록'), ('M4_APPROVED', '4M 승인'), ('M4_REJECTED', '4M 반려'), ('NC_CREATED', '부적합 등록'), ('CAPA_REQUESTED', 'CAPA 요청'), ('CAPA_OVERDUE', 'CAPA 기한 초과'), ('CLAIM_ISSUED', '클레임 발행'), ('ISIR_SUBMITTED', 'ISIR 등록'), ('ISIR_APPROVED', 'ISIR 승인'), ('ISIR_REJECTED', 'ISIR 반려'), ('OUTGOING_FAILED', '출하검사 불합격'), ('DELIVERY_RECEIVED', '납품서 접수'), ('LOW_STOCK', '재고 부족 경고'), ('VENDOR_DOWNGRADED', '협력사 등급 하락')], max_length=30, verbose_name='이벤트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('recipients', models.ManyToManyField(related_name='rules', to='admin_app.notificationrecipient', verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림 규칙',
                'verbose_name_plural': '알림 규칙',
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_CREATED', '발주 등록'), ('ORDER_APPROVED', '발주 승인'), ('INSPECTION_CREATED', '수입검사 등록'), ('INSPECTION_PASSED', '수입검사 합격'), ('INSPECTION_FAILED', '수입검사 불합격'), ('M4_CREATED', '4M 변경 등록'), ('M4_APPROVED', '4M 승인'), ('M4_REJECTED', '4M 반려'), ('NC_CREATED', '부적합 등록'), ('CAPA_REQUESTED', 'CAPA 요청'), ('CAPA_OVERDUE', 'CAPA 기한 초과'), ('CLAIM_ISSUED', '클레임 발행'), ('ISIR_SUBMITTED', 'ISIR 등록'), ('ISIR_APPROVED', 'ISIR 승인'), ('ISIR_REJECTED', 'ISIR 반려'), ('OUTGOING_FAILED', '출하검사 불합격'), ('DELIVERY_RECEIVED', '납품서 접수'), ('LOW_STOCK', '재고 부족 경고'), ('VENDOR_DOWNGRADED', '협력사 등급 하락')], max_length=30, verbose_name='이벤트')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신 이메일')),
                ('subject', models.CharField(max_length=300, verbose_name='제목')),
                ('body', models.TextField(blank=True, verbose_name='내용')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SENT', '발송완료'), ('FAILED', '발송실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='참조 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.notificationrecipient', verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림 발송 이력',
                'verbose_name_plural': '알림 발송 이력',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'reference_id'], name='admin_app_n_event_t_29270a_idx'), models.Index(fields=['status', 'created_at'], name='admin_app_n_status_a6fe2a_idx')],
            },
        ),
    ]
