# Generated by Django 6.0 on 2026-04-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='send_to_vendor',
            field=models.BooleanField(default=False, help_text='해당 건의 협력사 이메일로 자동 발송', verbose_name='협력사 자동 발송'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='rules', to='admin_app.notificationrecipient', verbose_name='내부 수신자'),
        ),
    ]
