# Generated by Django 6.0 on 2026-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_add_send_to_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='body_template',
            field=models.TextField(blank=True, help_text='변수: {part_no}, {mold_name}, {status}, {requester}, {repair_by} 등. 비워두면 기본 본문 사용', verbose_name='본문 템플릿'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='send_to_requester',
            field=models.BooleanField(default=False, help_text='해당 건의 의뢰자(등록자) 이메일로 자동 발송', verbose_name='의뢰자에게 발송'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='subject_template',
            field=models.CharField(blank=True, help_text='변수: {part_no}, {mold_name}, {status}, {priority} 등. 비워두면 기본 제목 사용', max_length=300, verbose_name='제목 템플릿'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', '발주 등록'), ('ORDER_APPROVED', '발주 승인'), ('INSPECTION_CREATED', '수입검사 등록'), ('INSPECTION_PASSED', '수입검사 합격'), ('INSPECTION_FAILED', '수입검사 불합격'), ('M4_CREATED', '4M 변경 등록'), ('M4_APPROVED', '4M 승인'), ('M4_REJECTED', '4M 반려'), ('NC_CREATED', '부적합 등록'), ('CAPA_REQUESTED', 'CAPA 요청'), ('CAPA_OVERDUE', 'CAPA 기한 초과'), ('CLAIM_ISSUED', '클레임 발행'), ('ISIR_SUBMITTED', 'ISIR 등록'), ('ISIR_APPROVED', 'ISIR 승인'), ('ISIR_REJECTED', 'ISIR 반려'), ('OUTGOING_FAILED', '출하검사 불합격'), ('DELIVERY_RECEIVED', '납품서 접수'), ('LOW_STOCK', '재고 부족 경고'), ('VENDOR_DOWNGRADED', '협력사 등급 하락'), ('MOLD_REPAIR_REQUESTED', '금형 수리의뢰 등록'), ('MOLD_REPAIR_RECEIVED', '금형 수리 접수'), ('MOLD_REPAIR_IN_PROGRESS', '금형 수리 진행'), ('MOLD_REPAIR_COMPLETED', '금형 수리 완료')], max_length=30, verbose_name='이벤트'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', '발주 등록'), ('ORDER_APPROVED', '발주 승인'), ('INSPECTION_CREATED', '수입검사 등록'), ('INSPECTION_PASSED', '수입검사 합격'), ('INSPECTION_FAILED', '수입검사 불합격'), ('M4_CREATED', '4M 변경 등록'), ('M4_APPROVED', '4M 승인'), ('M4_REJECTED', '4M 반려'), ('NC_CREATED', '부적합 등록'), ('CAPA_REQUESTED', 'CAPA 요청'), ('CAPA_OVERDUE', 'CAPA 기한 초과'), ('CLAIM_ISSUED', '클레임 발행'), ('ISIR_SUBMITTED', 'ISIR 등록'), ('ISIR_APPROVED', 'ISIR 승인'), ('ISIR_REJECTED', 'ISIR 반려'), ('OUTGOING_FAILED', '출하검사 불합격'), ('DELIVERY_RECEIVED', '납품서 접수'), ('LOW_STOCK', '재고 부족 경고'), ('VENDOR_DOWNGRADED', '협력사 등급 하락'), ('MOLD_REPAIR_REQUESTED', '금형 수리의뢰 등록'), ('MOLD_REPAIR_RECEIVED', '금형 수리 접수'), ('MOLD_REPAIR_IN_PROGRESS', '금형 수리 진행'), ('MOLD_REPAIR_COMPLETED', '금형 수리 완료')], max_length=30, verbose_name='이벤트'),
        ),
    ]
