# Generated by Django 6.0 on 2026-04-24 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_notificationrule_body_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='body_template',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='subject_template',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='수신자명'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('MOLD_REPAIR_REQUESTED', '금형 수리의뢰 등록'), ('MOLD_REPAIR_RECEIVED', '금형 수리 접수'), ('MOLD_REPAIR_IN_PROGRESS', '금형 수리 진행'), ('MOLD_REPAIR_COMPLETED', '금형 수리 완료'), ('ORDER_CREATED', '발주 등록'), ('ORDER_APPROVED', '발주 승인'), ('INSPECTION_CREATED', '수입검사 등록'), ('INSPECTION_PASSED', '수입검사 합격'), ('INSPECTION_FAILED', '수입검사 불합격'), ('M4_CREATED', '4M 변경 등록'), ('M4_APPROVED', '4M 승인'), ('M4_REJECTED', '4M 반려'), ('NC_CREATED', '부적합 등록'), ('CAPA_REQUESTED', 'CAPA 요청'), ('CAPA_OVERDUE', 'CAPA 기한 초과'), ('CLAIM_ISSUED', '클레임 발행'), ('ISIR_SUBMITTED', 'ISIR 등록'), ('ISIR_APPROVED', 'ISIR 승인'), ('ISIR_REJECTED', 'ISIR 반려'), ('OUTGOING_FAILED', '출하검사 불합격'), ('DELIVERY_RECEIVED', '납품서 접수'), ('LOW_STOCK', '재고 부족 경고'), ('VENDOR_DOWNGRADED', '협력사 등급 하락')], max_length=30, verbose_name='이벤트'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('MOLD_REPAIR_REQUESTED', '금형 수리의뢰 등록'), ('MOLD_REPAIR_RECEIVED', '금형 수리 접수'), ('MOLD_REPAIR_IN_PROGRESS', '금형 수리 진행'), ('MOLD_REPAIR_COMPLETED', '금형 수리 완료'), ('ORDER_CREATED', '발주 등록'), ('ORDER_APPROVED', '발주 승인'), ('INSPECTION_CREATED', '수입검사 등록'), ('INSPECTION_PASSED', '수입검사 합격'), ('INSPECTION_FAILED', '수입검사 불합격'), ('M4_CREATED', '4M 변경 등록'), ('M4_APPROVED', '4M 승인'), ('M4_REJECTED', '4M 반려'), ('NC_CREATED', '부적합 등록'), ('CAPA_REQUESTED', 'CAPA 요청'), ('CAPA_OVERDUE', 'CAPA 기한 초과'), ('CLAIM_ISSUED', '클레임 발행'), ('ISIR_SUBMITTED', 'ISIR 등록'), ('ISIR_APPROVED', 'ISIR 승인'), ('ISIR_REJECTED', 'ISIR 반려'), ('OUTGOING_FAILED', '출하검사 불합격'), ('DELIVERY_RECEIVED', '납품서 접수'), ('LOW_STOCK', '재고 부족 경고'), ('VENDOR_DOWNGRADED', '협력사 등급 하락')], max_length=30, unique=True, verbose_name='이벤트'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='recipients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='notification_rules', to=settings.AUTH_USER_MODEL, verbose_name='내부 수신자'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='send_to_requester',
            field=models.BooleanField(default=False, verbose_name='의뢰자에게 발송'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='send_to_vendor',
            field=models.BooleanField(default=False, verbose_name='협력사 자동 발송'),
        ),
        migrations.DeleteModel(
            name='NotificationRecipient',
        ),
    ]
