# Generated by ChatGPT on 2026-01-09
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "창고",
                "verbose_name_plural": "창고",
            },
        ),
        migrations.CreateModel(
            name="WmsItemLookup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("part_no", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="품번")),
                ("part_name", models.CharField(max_length=255, verbose_name="품명")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WMS 품목(조회용)",
                "verbose_name_plural": "WMS 품목(조회용)",
            },
        ),
        migrations.CreateModel(
            name="ErpStockSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_id", models.CharField(db_index=True, max_length=36)),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                ("warehouse_code", models.CharField(db_index=True, max_length=50)),
                ("part_no", models.CharField(db_index=True, max_length=100)),
                ("qty_onhand", models.DecimalField(decimal_places=3, max_digits=18)),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wms_stock_uploads", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "ERP 재고 스냅샷",
                "verbose_name_plural": "ERP 재고 스냅샷",
            },
        ),
        migrations.AddIndex(
            model_name="erpstocksnapshot",
            index=models.Index(fields=["snapshot_at", "warehouse_code", "part_no"], name="wms_stock_snap_wh_part_idx"),
        ),
        migrations.CreateModel(
            name="WmsReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("warehouse_code", models.CharField(db_index=True, max_length=50, verbose_name="입고창고")),
                ("part_no", models.CharField(db_index=True, max_length=100, verbose_name="품번")),
                ("part_name", models.CharField(max_length=255, verbose_name="품명")),
                ("receipt_qty", models.DecimalField(decimal_places=3, max_digits=18, verbose_name="입고수량")),
                ("receipt_date", models.DateField(verbose_name="입고일")),
                ("mfg_date", models.DateField(blank=True, null=True, verbose_name="제조일")),
                ("lot_no", models.CharField(blank=True, max_length=100, verbose_name="LOT No")),
                ("status", models.CharField(choices=[("draft", "임시저장"), ("requested", "검사의뢰"), ("approved", "입고완료"), ("rejected", "반려")], db_index=True, default="draft", max_length=20)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wms_receipts_approved", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wms_receipts_created", to=settings.AUTH_USER_MODEL)),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wms_receipts_rejected", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wms_receipts_requested", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "입고 등록",
                "verbose_name_plural": "입고 등록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WmsReceiptAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="wms/receipts/%Y/%m/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("receipt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="wms.wmsreceipt")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wms_receipt_files", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "입고 성적서(첨부)",
                "verbose_name_plural": "입고 성적서(첨부)",
            },
        ),
    ]
