# Generated by Django 6.0 on 2026-01-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erpstocksnapshot',
            new_name='wms_erpstoc_snapsho_7ba065_idx',
            old_name='wms_stock_snap_wh_part_idx',
        ),
    ]
