# Generated by Django 6.0 on 2026-01-12 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0020_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='창고명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='창고코드')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '창고(장소) 관리',
                'verbose_name_plural': '1. 창고(장소) 관리',
            },
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=30, unique=True, verbose_name='수불번호')),
                ('transaction_type', models.CharField(choices=[('IN_SCM', 'SCM 납품입고'), ('IN_MANUAL', '수기 입고'), ('OUT_PROD', '생산 불출'), ('TRANSFER', '창고 이동'), ('ADJUST', '재고 조정'), ('RETURN', '반품 출고')], max_length=20, verbose_name='구분')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='처리일시')),
                ('quantity', models.IntegerField(verbose_name='변동수량')),
                ('result_stock', models.IntegerField(default=0, verbose_name='변동후 잔량')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('ref_delivery_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='참조 납품서번호')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.vendor', verbose_name='관련 거래처')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tx_from', to='material.warehouse', verbose_name='보낸 창고')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tx_to', to='material.warehouse', verbose_name='받은 창고')),
            ],
            options={
                'verbose_name': '수불(입출고) 이력',
                'verbose_name_plural': '3. 수불(입출고) 이력',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='현재고')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': '창고별 재고 현황',
                'verbose_name_plural': '2. 창고별 재고 현황',
                'unique_together': {('warehouse', 'part')},
            },
        ),
    ]
