# Generated by Django 6.0 on 2026-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN_SCM', 'SCM 납품입고'), ('IN_MANUAL', '수기 입고'), ('OUT_PROD', '생산 불출'), ('TRANSFER', '창고 이동'), ('ADJUST', '재고 조정'), ('OUT_RETURN', '반품 출고')], max_length=20, verbose_name='구분'),
        ),
    ]
