# Generated by Django 6.0 on 2026-01-19 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_materialtransaction_transaction_type'),
        ('orders', '0028_change_lot_to_date_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='lot_no',
            field=models.DateField(blank=True, null=True, verbose_name='LOT 번호(생산일)'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='lot_no',
            field=models.DateField(blank=True, null=True, verbose_name='LOT 번호(생산일)'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='처리일시'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN_SCM', 'SCM 납품입고'), ('IN_MANUAL', '수기 입고'), ('OUT_PROD', '생산 불출'), ('TRANSFER', '창고 이동'), ('ADJUST', '재고 조정'), ('OUT_RETURN', '반품 출고')], db_index=True, max_length=20, verbose_name='구분'),
        ),
        migrations.AlterUniqueTogether(
            name='materialstock',
            unique_together={('warehouse', 'part', 'lot_no')},
        ),
    ]
