# Generated by Django 6.0 on 2026-01-21 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_add_lot_to_stock_and_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='모품번')),
                ('part_name', models.CharField(max_length=200, verbose_name='모품명')),
                ('spec', models.CharField(blank=True, max_length=100, null=True, verbose_name='규격')),
                ('unit', models.CharField(default='EA', max_length=20, verbose_name='재고단위')),
                ('account_type', models.CharField(choices=[('제품', '제품'), ('반제품', '반제품')], default='제품', max_length=20, verbose_name='계정구분')),
                ('procurement_type', models.CharField(default='생산', max_length=20, verbose_name='조달구분')),
                ('is_bom_registered', models.BooleanField(default=True, verbose_name='BOM등록여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '모품(제품) 마스터',
                'verbose_name_plural': '4. 모품(제품) 마스터',
                'ordering': ['part_no'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1, verbose_name='순번')),
                ('child_part_no', models.CharField(db_index=True, max_length=50, verbose_name='자품번')),
                ('child_part_name', models.CharField(max_length=200, verbose_name='자품명')),
                ('child_spec', models.CharField(blank=True, max_length=100, null=True, verbose_name='규격')),
                ('child_unit', models.CharField(default='EA', max_length=20, verbose_name='재고단위')),
                ('net_qty', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='정미수량')),
                ('loss_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='LOSS(%)')),
                ('required_qty', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='필요수량')),
                ('supply_type', models.CharField(choices=[('자재', '자재'), ('사급', '사급')], default='자재', max_length=20, verbose_name='사급구분')),
                ('outsource_type', models.CharField(default='무상', max_length=20, verbose_name='외주구분')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='주거래처')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일자')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일자')),
                ('drawing_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='도면번호')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='재질')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('is_bom_active', models.BooleanField(default=True, verbose_name='BOM사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='material.product', verbose_name='모품')),
            ],
            options={
                'verbose_name': 'BOM 구성품목',
                'verbose_name_plural': '5. BOM 구성품목',
                'ordering': ['product', 'seq'],
                'unique_together': {('product', 'seq', 'child_part_no')},
            },
        ),
    ]
