# Generated by Django 6.0 on 2026-01-21 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_bom_models'),
        ('orders', '0030_notice_qna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_month', models.DateField(unique=True, verbose_name='마감월')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='마감 처리일시')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='마감 처리자')),
            ],
            options={
                'verbose_name': '재고 마감',
                'verbose_name_plural': '6. 재고 마감',
                'ordering': ['-closing_month'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.DateField(blank=True, null=True, verbose_name='LOT 번호')),
                ('system_qty', models.IntegerField(default=0, verbose_name='시스템 재고')),
                ('actual_qty', models.IntegerField(default=0, verbose_name='실사 재고')),
                ('diff_qty', models.IntegerField(default=0, verbose_name='차이수량')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('MATCHED', '일치'), ('ADJUSTED', '조정완료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='실사일시')),
                ('adjusted_at', models.DateTimeField(blank=True, null=True, verbose_name='조정일시')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='실사자')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.warehouse', verbose_name='창고')),
                ('closing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='material.inventoryclosing', verbose_name='마감')),
            ],
            options={
                'verbose_name': '재고 실사 기록',
                'verbose_name_plural': '7. 재고 실사 기록',
                'ordering': ['-checked_at'],
            },
        ),
    ]
