# Generated by Django 6.0 on 2026-01-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_inventory_closing'),
        ('orders', '0030_notice_qna'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.DateField(blank=True, null=True, verbose_name='LOT 번호')),
                ('quantity', models.IntegerField(default=0, verbose_name='마감 시점 재고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='material.inventoryclosing', verbose_name='마감')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': '마감 재고 스냅샷',
                'verbose_name_plural': '8. 마감 재고 스냅샷',
                'ordering': ['-closing__closing_month', 'warehouse__code', 'part__part_no'],
                'unique_together': {('closing', 'warehouse', 'part', 'lot_no')},
            },
        ),
    ]
