# Generated by Django - ProcessTag and ProcessTagScanLog

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0036_link_existing_vendor_organization'),
        ('material', '0006_inventory_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='태그ID')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=200, verbose_name='품명')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('lot_no', models.DateField(blank=True, null=True, verbose_name='LOT 번호')),
                ('status', models.CharField(choices=[('PRINTED', '발행'), ('USED', '사용완료'), ('CANCELLED', '취소')], default='PRINTED', max_length=15, verbose_name='상태')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='발행일시')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 사용일시')),
                ('scan_count', models.IntegerField(default=0, verbose_name='스캔 횟수')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_printed', to=settings.AUTH_USER_MODEL, verbose_name='발행자')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_used', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('used_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.warehouse', verbose_name='사용 창고')),
            ],
            options={
                'verbose_name': '공정 현품표',
                'verbose_name_plural': '9. 공정 현품표',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTagScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='스캔일시')),
                ('is_first_scan', models.BooleanField(default=False, verbose_name='최초스캔여부')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP주소')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='스캔자')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='material.processtag', verbose_name='현품표')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': '현품표 스캔 이력',
                'verbose_name_plural': '10. 현품표 스캔 이력',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
