# Generated by Django 6.0 on 2026-01-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_processtag_processtagscanlog'),
        ('orders', '0037_change_request_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtag',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.part', verbose_name='품목'),
        ),
    ]
