# Generated by Django 6.0 on 2026-01-26 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_allow_null_part_in_processtag'),
        ('orders', '0038_add_qms_detailed_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_no', models.CharField(max_length=30, unique=True, verbose_name='조사번호')),
                ('check_date', models.DateField(verbose_name='조사일')),
                ('status', models.CharField(choices=[('DRAFT', '준비중'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='DRAFT', max_length=15, verbose_name='상태')),
                ('total_scanned', models.IntegerField(default=0, verbose_name='총 스캔건수')),
                ('total_matched', models.IntegerField(default=0, verbose_name='일치건수')),
                ('total_discrepancy', models.IntegerField(default=0, verbose_name='불일치건수')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_sessions_completed', to=settings.AUTH_USER_MODEL, verbose_name='완료자')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_sessions', to='material.warehouse', verbose_name='대상 창고')),
            ],
            options={
                'verbose_name': '재고조사 세션',
                'verbose_name_plural': '11. 재고조사 세션',
                'ordering': ['-check_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=30, verbose_name='태그ID')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=200, verbose_name='품명')),
                ('lot_no', models.DateField(blank=True, null=True, verbose_name='LOT번호')),
                ('scanned_qty', models.IntegerField(verbose_name='현품표 수량')),
                ('system_qty', models.IntegerField(default=0, verbose_name='시스템 수량')),
                ('discrepancy', models.IntegerField(default=0, verbose_name='차이')),
                ('is_matched', models.BooleanField(default=True, verbose_name='일치여부')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='스캔일시')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('check_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='material.inventorychecksession', verbose_name='조사')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.part', verbose_name='품목')),
                ('process_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.processtag', verbose_name='현품표')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='스캔자')),
            ],
            options={
                'verbose_name': '재고조사 세션 항목',
                'verbose_name_plural': '12. 재고조사 세션 항목',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
