# Generated by Django 6.0 on 2026-02-07 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_inventory_check_session'),
        ('orders', '0042_login_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('3F', '3공장'), ('2F', '2공장')], default='3F', max_length=10, verbose_name='구역')),
                ('position_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='위치코드')),
                ('row_label', models.CharField(max_length=10, verbose_name='행 라벨')),
                ('row_num', models.IntegerField(default=1, verbose_name='행 번호')),
                ('col_num', models.IntegerField(default=1, verbose_name='열 번호')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_positions', to='orders.part', verbose_name='배치 품목')),
            ],
            options={
                'verbose_name': '원재료 랙 위치',
                'verbose_name_plural': '13. 원재료 랙 위치',
                'ordering': ['section', 'row_label', '-row_num', '-col_num'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='라벨ID')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=200, verbose_name='품명')),
                ('lot_no', models.DateField(verbose_name='LOT번호(입고일)')),
                ('quantity', models.DecimalField(decimal_places=2, default=25, max_digits=10, verbose_name='수량(kg)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='유효기간')),
                ('status', models.CharField(choices=[('PRINTED', '발행'), ('INSTOCK', '재고'), ('USED', '사용완료'), ('EXPIRED', '유효기간만료'), ('DISPOSED', '폐기')], default='PRINTED', max_length=15, verbose_name='상태')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='발행일시')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일시')),
                ('incoming_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialtransaction', verbose_name='입고 트랜잭션')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawmaterial_labels_printed', to=settings.AUTH_USER_MODEL, verbose_name='발행자')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawmaterial_labels_used', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.vendor', verbose_name='거래처')),
                ('current_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.rawmaterialrack', verbose_name='현재 위치')),
            ],
            options={
                'verbose_name': '원재료 QR 라벨',
                'verbose_name_plural': '15. 원재료 QR 라벨',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_stock', models.IntegerField(default=0, help_text='이 수량 이하면 경고', verbose_name='안전재고')),
                ('warning_stock', models.IntegerField(default=0, help_text='이 수량 이하면 주의 (안전재고보다 높게)', verbose_name='경고재고')),
                ('shelf_life_days', models.IntegerField(default=365, help_text='입고일로부터 유효기간', verbose_name='보관기간(일)')),
                ('unit_weight', models.DecimalField(decimal_places=2, default=25, help_text='포대당 중량 (기본 25kg)', max_digits=10, verbose_name='단위중량(kg)')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_setting', to='orders.part', verbose_name='품목')),
            ],
            options={
                'verbose_name': '원재료 품목 설정',
                'verbose_name_plural': '14. 원재료 품목 설정',
            },
        ),
    ]
