# Generated by Django 6.0 on 2026-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_raw_material_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialrack',
            name='position_code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='위치코드'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialrack',
            unique_together={('section', 'position_code')},
        ),
    ]
