# Generated by Django 6.0 on 2026-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_raw_material_rack_section_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmateriallabel',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('EA', 'EA'), ('L', 'L'), ('M', 'm')], default='KG', max_length=5, verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='rawmateriallabel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10, verbose_name='수량'),
        ),
    ]
