# Generated by Django 6.0 on 2026-02-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_add_unit_to_rawmateriallabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmateriallabel',
            name='used_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_labels', to='material.materialtransaction', verbose_name='사용(이동) 트랜잭션'),
        ),
        migrations.AlterField(
            model_name='rawmateriallabel',
            name='incoming_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_labels', to='material.materialtransaction', verbose_name='입고 트랜잭션'),
        ),
    ]
