# Generated by Django 6.0 on 2026-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_add_used_transaction_to_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_production',
            field=models.BooleanField(default=False, help_text='체크하면 재고이동 시 라벨 선택 모달이 표시됩니다.', verbose_name='제조현장 여부'),
        ),
    ]
