# Generated by Django 6.0 on 2026-02-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_add_warehouse_is_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtag',
            name='used_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tags', to='material.materialtransaction', verbose_name='사용(이동) 트랜잭션'),
        ),
    ]
