# Generated by Django 6.0 on 2026-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_add_used_transaction_to_processtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='erp_incoming_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ERP입고번호'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='erp_sync_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ERP연동메시지'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='erp_sync_status',
            field=models.CharField(choices=[('NONE', '미대상'), ('PENDING', '대기'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='NONE', max_length=10, verbose_name='ERP연동상태'),
        ),
        migrations.AlterField(
            model_name='rawmateriallabel',
            name='status',
            field=models.CharField(choices=[('PRINTED', '발행'), ('INSTOCK', '재고'), ('USED', '사용완료'), ('CANCELLED', '취소'), ('EXPIRED', '유효기간만료'), ('DISPOSED', '폐기')], default='PRINTED', max_length=15, verbose_name='상태'),
        ),
    ]
