# Generated by Django 6.0 on 2026-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0023_alter_materialtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtag',
            name='stock_reflected',
            field=models.BooleanField(default=False, verbose_name='재고반영완료'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN_SCM', 'SCM 납품입고'), ('IN_MANUAL', '수기 입고'), ('IN_ERP', 'ERP 입고'), ('OUT_PROD', '생산 불출'), ('TRANSFER', '창고 이동'), ('ADJUST', '재고 조정'), ('ADJ_ERP_IN', 'ERP 조정입고'), ('ADJ_ERP_OUT', 'ERP 조정출고'), ('ISU_ERP', 'ERP 생산출고'), ('RCV_ERP', 'ERP 생산입고'), ('TRF_ERP', 'ERP 재고이동'), ('OUT_ERP', 'ERP 출고'), ('OUT_MANUAL', 'SCM 수기출고'), ('OUT_RETURN', '반품 출고'), ('LOT_ASSIGN', 'LOT 배분')], db_index=True, max_length=20, verbose_name='구분'),
        ),
    ]
