# Generated by Django 6.0 on 2026-02-26 15:39

from django.db import migrations


def set_existing_used_tags_reflected(apps, schema_editor):
    """기존 USED 상태 태그는 이미 처리된 것이므로 stock_reflected=True로 설정"""
    ProcessTag = apps.get_model('material', 'ProcessTag')
    ProcessTag.objects.filter(status='USED').update(stock_reflected=True)


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0024_add_stock_reflected_to_processtag'),
    ]

    operations = [
        migrations.RunPython(set_existing_used_tags_reflected, migrations.RunPython.noop),
    ]
