# Generated by Django 6.0 on 2026-03-01 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0026_alter_materialtransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialrack',
            name='display_override',
            field=models.IntegerField(blank=True, help_text='감사모드 시 실재고 대신 표시할 기준 수량(kg)', null=True, verbose_name='표시재고 오버라이드'),
        ),
        migrations.CreateModel(
            name='WMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_mode', models.BooleanField(default=False, help_text='ON이면 레이아웃에 오버라이드 수량 표시', verbose_name='감사모드')),
                ('audit_mode_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='감사모드 변경일시')),
                ('audit_mode_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='감사모드 변경자')),
            ],
            options={
                'verbose_name': 'WMS 전역 설정',
                'verbose_name_plural': '16. WMS 전역 설정',
            },
        ),
    ]
