# Generated by Django 6.0 on 2026-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0027_audit_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialrack',
            old_name='display_override',
            new_name='display_adjustment',
        ),
        migrations.AlterField(
            model_name='rawmaterialrack',
            name='display_adjustment',
            field=models.IntegerField(blank=True, help_text='감사모드 시 실재고에 더할 보정값(kg). 양수=증가, 음수=감소', null=True, verbose_name='표시재고 보정값'),
        ),
    ]
