# Generated by Django 6.0 on 2026-03-10 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0028_rename_display_override_to_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldingDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='일자')),
                ('shift', models.CharField(choices=[('주간', '주간'), ('야간', '야간')], max_length=10, verbose_name='근무구분')),
                ('status', models.CharField(default='비가동', max_length=10, verbose_name='가동구분')),
                ('operating_minutes', models.IntegerField(default=0, verbose_name='가동시간(분)')),
                ('loss_minutes', models.IntegerField(default=0, verbose_name='유실시간(분)')),
                ('utilization_rate', models.FloatField(default=0, verbose_name='설비가동률')),
                ('time_rate', models.FloatField(default=0, verbose_name='시간가동률')),
                ('product_part_no', models.CharField(blank=True, max_length=50, verbose_name='생산품번')),
                ('product_qty', models.IntegerField(default=0, verbose_name='생산수량')),
            ],
            options={
                'verbose_name': '성형 일별 가동기록',
                'verbose_name_plural': '17. 성형 일별 가동기록',
                'ordering': ['-date', 'machine', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='MoldingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='호기')),
                ('tonnage', models.IntegerField(default=0, verbose_name='톤수')),
                ('line', models.CharField(blank=True, max_length=20, verbose_name='라인')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '성형기',
                'verbose_name_plural': '17. 성형기 마스터',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MoldingLossDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='유실사유')),
                ('minutes', models.IntegerField(default=0, verbose_name='시간(분)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_details', to='material.moldingdailyrecord')),
            ],
            options={
                'verbose_name': '유실 상세',
                'verbose_name_plural': '17. 유실 상세',
            },
        ),
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='material.moldingmachine'),
        ),
        migrations.CreateModel(
            name='MoldingUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('record_count', models.IntegerField(default=0, verbose_name='등록건수')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='파일명')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '가동률 업로드 이력',
                'verbose_name_plural': '17. 가동률 업로드 이력',
            },
        ),
        migrations.AlterUniqueTogether(
            name='moldingdailyrecord',
            unique_together={('machine', 'date', 'shift')},
        ),
    ]
