# Generated by Django 6.0 on 2026-03-10 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0029_add_molding_utilization_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moldingdailyrecord',
            options={'ordering': ['-date', 'machine'], 'verbose_name': '성형 일별 가동기록', 'verbose_name_plural': '17. 성형 일별 가동기록'},
        ),
        migrations.AlterUniqueTogether(
            name='moldingdailyrecord',
            unique_together={('machine', 'date')},
        ),
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='base_minutes',
            field=models.IntegerField(default=0, verbose_name='기준시간(분)'),
        ),
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='erp_synced',
            field=models.BooleanField(default=False, verbose_name='ERP동기화여부'),
        ),
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='input_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입력일시'),
        ),
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='input_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='input_completed',
            field=models.BooleanField(default=False, verbose_name='입력완료'),
        ),
        migrations.AlterField(
            model_name='moldingdailyrecord',
            name='product_part_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='생산품번'),
        ),
        migrations.AlterField(
            model_name='moldingdailyrecord',
            name='time_rate',
            field=models.FloatField(default=0, verbose_name='시간가동률(%)'),
        ),
        migrations.AlterField(
            model_name='moldingdailyrecord',
            name='utilization_rate',
            field=models.FloatField(default=0, verbose_name='설비가동률(%)'),
        ),
        migrations.AlterField(
            model_name='moldinglossdetail',
            name='category',
            field=models.CharField(choices=[('계획정지', '계획정지'), ('생산종료', '생산종료'), ('식사휴식', '식사/휴식'), ('청소', '청소'), ('인원부족', '인원부족'), ('금형예열', '금형예열'), ('금형수리', '금형수리'), ('기종변경', '기종변경'), ('기타', '기타'), ('재료결품', '재료결품'), ('재료건조', '재료건조'), ('품질이상', '품질이상'), ('설비고장', '설비고장'), ('자재부족', '자재부족'), ('TRY', 'TRY')], max_length=30, verbose_name='유실사유'),
        ),
        migrations.CreateModel(
            name='MoldingERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='동기화일시')),
                ('record_count', models.IntegerField(default=0, verbose_name='동기화건수')),
                ('machine_count', models.IntegerField(default=0, verbose_name='가동호기수')),
                ('message', models.TextField(blank=True, verbose_name='메시지')),
                ('synced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP 동기화 이력',
                'verbose_name_plural': '17. ERP 동기화 이력',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='MoldingWorkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('day_shift_minutes', models.IntegerField(default=670, verbose_name='주간 기준시간(분)')),
                ('night_shift_minutes', models.IntegerField(default=770, verbose_name='야간 기준시간(분)')),
                ('work_days', models.IntegerField(default=20, verbose_name='근무일수')),
            ],
            options={
                'verbose_name': '성형 근무 설정',
                'verbose_name_plural': '17. 성형 근무 설정',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.RemoveField(
            model_name='moldingdailyrecord',
            name='shift',
        ),
    ]
