# Generated by Django 6.0 on 2026-03-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0030_molding_redesign_web_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmateriallabel',
            name='label_type',
            field=models.CharField(choices=[('PACKAGE', '포장'), ('PALLET', '파렛트')], default='PACKAGE', max_length=10, verbose_name='라벨유형'),
        ),
    ]
