# Generated by Django 6.0 on 2026-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0031_add_label_type_to_rawmateriallabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='shift',
            field=models.CharField(choices=[('주간', '주간'), ('야간', '야간')], default='주간', max_length=10, verbose_name='근무구분'),
        ),
    ]
