# Generated by Django 6.0 on 2026-04-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0032_add_shift_to_moldingdailyrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moldingdailyrecord',
            unique_together={('machine', 'date', 'shift')},
        ),
    ]
