# Generated by Django 6.0 on 2026-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0033_change_molding_unique_to_include_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moldingdailyrecord',
            name='product_part_no',
            field=models.CharField(blank=True, max_length=500, verbose_name='생산품번'),
        ),
    ]
