# Generated by Django 6.0 on 2026-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0034_extend_product_part_no_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='work_minutes',
            field=models.IntegerField(default=0, verbose_name='실가동시간(분)'),
        ),
    ]
