# Generated by Django 6.0 on 2026-04-07 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0035_add_work_minutes_to_moldingdailyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(db_index=True, max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(blank=True, max_length=200, verbose_name='품명')),
                ('item_group', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='품목')),
                ('mold_type', models.CharField(blank=True, choices=[('단일', '단일'), ('패밀리', '패밀리')], max_length=10, verbose_name='금형구분')),
                ('material_type', models.CharField(blank=True, choices=[('재료1', '재료1'), ('M/B', 'M/B'), ('재료2', '재료2')], max_length=10, verbose_name='재료구분')),
                ('material_part_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='재료품번')),
                ('material_name', models.CharField(blank=True, max_length=200, verbose_name='재료품명')),
                ('machine_tonnage', models.IntegerField(default=0, verbose_name='설비톤수')),
                ('cycle_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='CT(초)')),
                ('cavity', models.IntegerField(default=0, verbose_name='캐비티수')),
                ('shot_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ST')),
                ('gate_type', models.CharField(blank=True, choices=[('자동', '자동'), ('분리', '분리'), ('수동(G/CUT)', '수동(G/CUT)')], max_length=20, verbose_name='게이트')),
                ('hot_runner_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='HT')),
                ('product_weight', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='제품중량(g)')),
                ('tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='공차')),
                ('runner_weight', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='런너중량(g)')),
                ('total_material', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='총소요량(g)')),
                ('erp_qty', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='ERP수량(kg)')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molding_masters', to='material.moldingmachine', verbose_name='설비호기')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '성형 마스터',
                'verbose_name_plural': '17. 성형 마스터',
                'ordering': ['part_no', 'material_type'],
                'unique_together': {('part_no', 'material_type')},
            },
        ),
    ]
