# Generated by Django 6.0 on 2026-04-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0036_moldingmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='기종(전체)')),
                ('item_group_detail', models.CharField(blank=True, max_length=50, verbose_name='기종(세부)')),
                ('mold_name', models.CharField(max_length=200, verbose_name='금형명')),
                ('part_no', models.CharField(db_index=True, max_length=50, verbose_name='부품번호')),
                ('transfer_date', models.CharField(blank=True, max_length=20, verbose_name='이관일자')),
                ('transfer_from', models.CharField(blank=True, max_length=50, verbose_name='이관처')),
                ('guarantee_shots', models.IntegerField(default=500000, verbose_name='보증수명(숏)')),
                ('cv_count', models.IntegerField(default=1, verbose_name='C/V수')),
                ('material_type', models.CharField(blank=True, max_length=30, verbose_name='재료구분')),
                ('total_shots_prev', models.IntegerField(default=0, verbose_name='총사용숏트수(이전)')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='등급')),
                ('last_mt_shots', models.IntegerField(default=0, verbose_name='최근MT시점 누적숏트')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '금형 마스터',
                'verbose_name_plural': '18. 금형 마스터',
                'ordering': ['item_group', 'part_no'],
            },
        ),
        migrations.CreateModel(
            name='MoldMTSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=30, verbose_name='재료구분')),
                ('grade_a', models.IntegerField(default=40000, verbose_name='A등급 기준')),
                ('grade_b', models.IntegerField(default=40000, verbose_name='B등급 기준')),
                ('grade_c', models.IntegerField(default=40000, verbose_name='C등급 기준')),
                ('grade_d', models.IntegerField(default=30000, verbose_name='D등급 기준')),
                ('grade_e', models.IntegerField(default=30000, verbose_name='E등급 기준')),
            ],
            options={
                'verbose_name': 'MT 기준 설정',
                'verbose_name_plural': '18. MT 기준 설정',
                'ordering': ['material_type'],
            },
        ),
        migrations.CreateModel(
            name='MoldMTLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_date', models.DateField(verbose_name='MT일자')),
                ('accumulated_shots', models.IntegerField(default=0, verbose_name='MT시점 누적숏트')),
                ('description', models.TextField(blank=True, verbose_name='작업내용')),
                ('performed_by', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_logs', to='material.moldmaster')),
            ],
            options={
                'verbose_name': 'MT 이력',
                'verbose_name_plural': '18. MT 이력',
                'ordering': ['-mt_date'],
            },
        ),
        migrations.CreateModel(
            name='MoldShotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('shots', models.IntegerField(default=0, verbose_name='숏트수')),
                ('source', models.CharField(choices=[('EXCEL', '엑셀'), ('ERP', 'ERP')], default='EXCEL', max_length=10, verbose_name='소스')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_records', to='material.moldmaster')),
            ],
            options={
                'verbose_name': '숏트수 이력',
                'verbose_name_plural': '18. 숏트수 이력',
                'ordering': ['year', 'month'],
                'unique_together': {('mold', 'year', 'month')},
            },
        ),
    ]
