# Generated by Django 6.0 on 2026-04-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0037_moldmaster_moldmtsetting_moldmtlog_moldshotrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(db_index=True, max_length=50, verbose_name='품번')),
                ('mold_name', models.CharField(blank=True, max_length=200, verbose_name='금형명')),
                ('item_group', models.CharField(blank=True, max_length=50, verbose_name='품목')),
                ('priority', models.CharField(choices=[('A', 'A (긴급)'), ('B', 'B (보통)'), ('C', 'C (낮음)')], default='B', max_length=1, verbose_name='중요도')),
                ('status', models.CharField(choices=[('REQUESTED', '의뢰등록'), ('RECEIVED', '접수'), ('IN_PROGRESS', '수리중'), ('COMPLETED', '완료')], default='REQUESTED', max_length=20, verbose_name='진행상태')),
                ('request_content', models.TextField(verbose_name='의뢰내용')),
                ('repair_types', models.CharField(blank=True, help_text='콤마 구분: BURR,미각기,파손 등', max_length=200, verbose_name='수리유형')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='의뢰일시')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='접수일')),
                ('repair_request_date', models.DateField(blank=True, null=True, verbose_name='수리요청일')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='완료예정일')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='완료일')),
                ('repair_content', models.TextField(blank=True, verbose_name='수리내용')),
                ('repair_by', models.CharField(blank=True, max_length=50, verbose_name='수리담당자')),
                ('hr_milling', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='밀링')),
                ('hr_lathe', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='선반')),
                ('hr_grinding', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='연마')),
                ('hr_welding', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='사내용접')),
                ('hr_high_speed', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='고속가공기')),
                ('hr_edm', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='방전')),
                ('hr_wire', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='WIRE')),
                ('hr_mt', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='M/T')),
                ('hr_polishing', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='사상')),
                ('hr_assembly', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='조립')),
                ('hr_other', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='기타HR')),
                ('cost_welding', models.IntegerField(default=0, verbose_name='외주용접')),
                ('cost_tapping', models.IntegerField(default=0, verbose_name='탭핑')),
                ('cost_milpin', models.IntegerField(default=0, verbose_name='밀핀')),
                ('cost_purchase', models.IntegerField(default=0, verbose_name='구매품')),
                ('cost_outsource', models.IntegerField(default=0, verbose_name='외주가공')),
                ('shot_count', models.IntegerField(default=0, verbose_name='SHOT수')),
                ('first_article', models.CharField(blank=True, max_length=20, verbose_name='초물확인')),
                ('ng_content', models.TextField(blank=True, verbose_name='NG내용 및 비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('mold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_requests', to='material.moldmaster')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mold_repair_requests', to=settings.AUTH_USER_MODEL, verbose_name='의뢰자')),
            ],
            options={
                'verbose_name': '금형 수리 의뢰',
                'verbose_name_plural': '19. 금형 수리 의뢰',
                'ordering': ['-requested_at'],
            },
        ),
    ]
