# Generated by Django 6.0 on 2026-04-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0038_moldrepairrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldingdailyrecord',
            name='defect_qty',
            field=models.IntegerField(default=0, verbose_name='불량수량'),
        ),
    ]
