# Generated by Django 6.0 on 2026-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0040_materialtransferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransferrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
