# Generated by Django 6.0 on 2026-06-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0041_materialtransferrequest'),
        ('orders', '0047_add_vendor_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtransferrequest',
            name='approved_qty',
        ),
        migrations.RemoveField(
            model_name='materialtransferrequest',
            name='part',
        ),
        migrations.RemoveField(
            model_name='materialtransferrequest',
            name='requested_qty',
        ),
        migrations.RemoveField(
            model_name='materialtransferrequest',
            name='transfer_transaction',
        ),
        migrations.CreateModel(
            name='MaterialTransferRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.IntegerField(verbose_name='신청수량')),
                ('remark', models.TextField(blank=True, verbose_name='비고')),
                ('lot_no', models.DateField(blank=True, null=True, verbose_name='승인 LOT')),
                ('approved_qty', models.IntegerField(blank=True, null=True, verbose_name='승인수량')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='material.materialtransferrequest', verbose_name='이동요청')),
                ('transfer_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request_lines', to='material.materialtransaction', verbose_name='이동 트랜잭션')),
            ],
            options={
                'verbose_name': '재료 이동 요청 항목',
                'verbose_name_plural': '재료 이동 요청 항목',
                'ordering': ['pk'],
            },
        ),
    ]
