# Generated by Django 6.0 on 2026-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0042_transfer_request_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransferrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('PARTIAL', '부분승인'), ('APPROVED', '승인완료'), ('REJECTED', '반려'), ('CANCELLED', '취소')], db_index=True, default='PENDING', max_length=15, verbose_name='상태'),
        ),
    ]
