# Generated by Django 6.0 on 2026-06-12 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0044_transfer_request_approver'),
        ('orders', '0049_purchase_order_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='신청번호')),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨'), ('CANCELLED', '취소됨')], db_index=True, default='PENDING', max_length=15, verbose_name='상태')),
                ('part_no', models.CharField(max_length=100, verbose_name='품번')),
                ('part_name', models.CharField(max_length=200, verbose_name='품명')),
                ('unit', models.CharField(default='EA', max_length=20, verbose_name='단위')),
                ('vendor_name', models.CharField(blank=True, max_length=200, verbose_name='거래처')),
                ('current_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='신청 시 현재고')),
                ('safety_stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='안전재고')),
                ('shortage_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='부족수량')),
                ('request_qty', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='발주신청 수량')),
                ('reason', models.TextField(blank=True, verbose_name='신청사유')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인/반려 일시')),
                ('reject_reason', models.TextField(blank=True, verbose_name='반려사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='orders.part', verbose_name='품목')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '발주신청',
                'verbose_name_plural': '21. 발주신청',
                'ordering': ['-created_at'],
            },
        ),
    ]
