# Generated by Django 6.0 on 2026-06-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0046_purchaseorderrequest_add_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldingProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cd', models.CharField(max_length=30, verbose_name='품번')),
                ('item_nm', models.CharField(blank=True, max_length=100, verbose_name='품명')),
                ('good_qty', models.IntegerField(default=0, verbose_name='양품수량')),
                ('bad_qty', models.IntegerField(default=0, verbose_name='불량수량')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='material.moldingdailyrecord')),
            ],
            options={
                'verbose_name': '품번별 생산실적',
                'verbose_name_plural': '17. 품번별 생산실적',
                'unique_together': {('record', 'item_cd')},
            },
        ),
    ]
