# Generated by Django 6.0 on 2026-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0047_add_molding_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_hidden_stock',
            field=models.BooleanField(default=False, help_text='체크하면 대시보드/재고조회/ERP 비교 등 재고 표시 화면에서 이 창고의 재고가 제외됩니다. (예: 연말 결산용 격리 창고)', verbose_name='재고 미표시'),
        ),
    ]
