# Generated by Django 6.0 on 2026-08-20 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0048_warehouse_is_hidden_stock'),
        ('orders', '0051_alter_deliveryorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='production_lot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='생산 LOT(배치)'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='production_lot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='생산 LOT(배치)'),
        ),
        migrations.AlterUniqueTogether(
            name='materialstock',
            unique_together={('warehouse', 'part', 'lot_no', 'production_lot')},
        ),
        migrations.CreateModel(
            name='ProductionLotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_lot_item', to='orders.part', verbose_name='품목')),
            ],
            options={
                'verbose_name': 'LOT 관리품목',
                'verbose_name_plural': 'LOT 관리품목',
                'ordering': ['part__part_no'],
            },
        ),
    ]
