# Generated by Django 6.0 on 2026-09-10 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def check_stock_identity(apps, schema_editor):
    stock = apps.get_model('material', 'MaterialStock')
    duplicates = stock.objects.using(schema_editor.connection.alias).order_by().values(
        'warehouse_id', 'part_id', 'lot_no', 'production_lot'
    ).annotate(rows=models.Count('pk')).filter(rows__gt=1)
    if duplicates.exists():
        raise RuntimeError('Duplicate stock identities exist. Audit quantities and history before applying this migration; no rows were merged or deleted.')


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0050_materialtransaction_source_incoming'),
        ('orders', '0052_labelprintlog_delivery_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_stock_identity, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ERPIncomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERPIncomingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REGISTER', '입고 등록'), ('DELETE', '입고 삭제')], max_length=10)),
                ('transaction_no', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', '전송 대기'), ('RUNNING', '전송 중'), ('SUCCESS', '완료'), ('FAILED', '실패'), ('REVIEW', 'ERP 확인 필요'), ('CANCELLED', '전송 취소')], db_index=True, default='PENDING', max_length=12)),
                ('erp_no', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ERP 입고 연동 요청',
                'verbose_name_plural': 'ERP 입고 연동 요청',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='delivery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='orders.deliveryorderitem', verbose_name='원본 납품서 품목'),
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('lot_no__isnull', False), ('production_lot__isnull', True)), fields=('warehouse', 'part', 'lot_no'), name='stock_unique_without_batch'),
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('lot_no__isnull', True), ('production_lot__isnull', False)), fields=('warehouse', 'part', 'production_lot'), name='stock_unique_without_date'),
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(condition=models.Q(('lot_no__isnull', True), ('production_lot__isnull', True)), fields=('warehouse', 'part'), name='stock_unique_without_lot'),
        ),
        migrations.AddField(
            model_name='erpincomingevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpincomingoperation',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.erpincomingoperation'),
        ),
        migrations.AddField(
            model_name='erpincomingoperation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_operations', to='material.materialtransaction'),
        ),
        migrations.AddField(
            model_name='erpincomingevent',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='material.erpincomingoperation'),
        ),
        migrations.AddConstraint(
            model_name='erpincomingoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'REGISTER'), ('status__in', ['PENDING', 'RUNNING', 'FAILED', 'REVIEW'])), fields=('transaction',), name='one_active_erp_receipt_request'),
        ),
        migrations.AddConstraint(
            model_name='erpincomingoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'DELETE')), fields=('erp_no',), name='one_erp_receipt_delete_request'),
        ),
    ]
