# Generated by Django 6.0 on 2026-09-14 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0051_receipt_integrity_and_erp_outbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementExpiryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=30, verbose_name='수불번호')),
                ('previous_date', models.DateField(blank=True, null=True, verbose_name='이전 유효기간')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='지정 유효기간')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='변경 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiry_events', to='material.materialtransaction')),
            ],
            options={
                'verbose_name': '이동 유효기간 변경 이력',
                'verbose_name_plural': '이동 유효기간 변경 이력',
                'ordering': ['-pk'],
            },
        ),
    ]
