# Generated by Django 6.0 on 2026-09-14 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0052_movementexpiryevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementVisibilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=30, verbose_name='수불번호')),
                ('previous_hidden', models.BooleanField(default=False, verbose_name='이전 숨김 상태')),
                ('hidden', models.BooleanField(default=False, verbose_name='숨김')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_events', to='material.materialtransaction')),
            ],
            options={
                'verbose_name': '유효기간 이력 숨김 변경 기록',
                'verbose_name_plural': '유효기간 이력 숨김 변경 기록',
                'ordering': ['-pk'],
            },
        ),
    ]
