# Generated by Django 6.0 on 2026-09-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0054_movement_expiry_manufacturing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsconfig',
            name='expiry_display_revision',
            field=models.PositiveIntegerField(default=0, verbose_name='유효기간 표시 설정 버전'),
        ),
        migrations.AddField(
            model_name='wmsconfig',
            name='show_expiry_references',
            field=models.BooleanField(default=True, verbose_name='유효기간 이력 ERP/SCM·수불번호 표시'),
        ),
    ]
