# Generated by Django 6.0 on 2025-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(default='V000', max_length=20, unique=True, verbose_name='업체코드'),
        ),
    ]
