# Generated by Django 6.0 on 2025-12-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(max_length=100, verbose_name='품명')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.vendor', verbose_name='전담 업체')),
            ],
            options={
                'verbose_name': '품목 마스터',
                'verbose_name_plural': '품목 마스터 관리',
                'unique_together': {('vendor', 'part_no')},
            },
        ),
    ]
