# Generated by Django 6.0 on 2025-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '발주서', 'verbose_name_plural': '발주서 관리'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': '협력사', 'verbose_name_plural': '협력사 관리'},
        ),
        migrations.AddField(
            model_name='order',
            name='part_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='품목군'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_group',
            field=models.CharField(default='일반', max_length=50, verbose_name='품목군'),
        ),
    ]
