# Generated by Django 6.0 on 2025-12-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발주등록일'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_stock', models.IntegerField(default=0, verbose_name='기초재고')),
                ('in_qty', models.IntegerField(default=0, verbose_name='입고수량')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종갱신일')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
            ],
            options={
                'verbose_name': '재고 관리',
                'verbose_name_plural': '재고/과부족 관리',
            },
        ),
    ]
