# Generated by Django 6.0 on 2025-12-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '기초재고 관리', 'verbose_name_plural': '1. 기초재고 관리'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='in_qty',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='base_stock',
            field=models.IntegerField(default=0, verbose_name='기초재고(현재고)'),
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField(verbose_name='입고예정일')),
                ('quantity', models.IntegerField(verbose_name='입고수량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
            ],
            options={
                'verbose_name': '일자별 입고 관리',
                'verbose_name_plural': '2. 일자별 입고 관리',
            },
        ),
    ]
