# Generated by Django 6.0 on 2025-12-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_inventory_options_remove_inventory_in_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_inventory_date',
            field=models.DateField(blank=True, null=True, verbose_name='재고실사기준일'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='발주마감여부'),
        ),
    ]
