# Generated by Django 6.0 on 2025-12-18 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_inventory_last_inventory_date_order_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('printed_qty', models.IntegerField(verbose_name='발행수량')),
                ('snp', models.IntegerField(verbose_name='포장단위(SNP)')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='발행일시')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.vendor', verbose_name='협력사')),
            ],
            options={
                'verbose_name': '라벨 발행 이력',
                'verbose_name_plural': '3. 라벨 발행 이력',
            },
        ),
    ]
