# Generated by Django 6.0 on 2025-12-18 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_labelprintlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='납품서 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '납품서',
                'verbose_name_plural': '4. 납품서 관리',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100, verbose_name='품번')),
                ('part_name', models.CharField(max_length=200, verbose_name='품명')),
                ('snp', models.IntegerField(default=0, verbose_name='SNP(박스당수량)')),
                ('box_count', models.IntegerField(default=0, verbose_name='박스 수')),
                ('total_qty', models.IntegerField(default=0, verbose_name='총 수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.deliveryorder', verbose_name='납품서 번호')),
            ],
            options={
                'verbose_name': '납품서 상세 품목',
                'verbose_name_plural': '납품서 상세 품목',
            },
        ),
    ]
