# Generated by Django 6.0 on 2025-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_deliveryorder_deliveryorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='입고완료여부'),
        ),
    ]
