# Generated by Django 6.0 on 2025-12-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_deliveryorder_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='can_view_inventory',
            field=models.BooleanField(default=True, verbose_name='과부족 조회 권한'),
        ),
    ]
