# Generated by Django 6.0 on 2025-12-18 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_vendor_can_view_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='소요 발생일(납기일)')),
                ('quantity', models.IntegerField(verbose_name='필요 소요량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
            ],
            options={
                'verbose_name': '소요량 관리',
                'verbose_name_plural': '소요량 관리',
            },
        ),
    ]
