# Generated by Django 6.0 on 2025-12-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='biz_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='biz_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업태'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='erp_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ERP 업체코드'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='representative',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='성명(대표이사)'),
        ),
    ]
