# Generated by Django 6.0 on 2025-12-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_vendor_address_vendor_biz_item_vendor_biz_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_scm_admin',
            field=models.BooleanField(default=False, verbose_name='[메뉴] 통합 관리자 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_incoming',
            field=models.BooleanField(default=False, verbose_name='[메뉴] 입고 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_register_orders',
            field=models.BooleanField(default=False, verbose_name='[메뉴] 발주서 등록'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_inventory',
            field=models.BooleanField(default=False, verbose_name='[메뉴] 과부족 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_orders',
            field=models.BooleanField(default=False, verbose_name='[메뉴] 발주 조회/승인'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', '1. 슈퍼관리자 (모든 메뉴 노출)'), ('STAFF', '2. 진영전기 직원 (운영 메뉴 노출)'), ('VENDOR', '3. 협력업체 (제한적 메뉴 노출)')], default='VENDOR', max_length=10, verbose_name='사용자 그룹'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_jinyoung_staff',
            field=models.BooleanField(default=False, verbose_name='진영전기 직원 여부(기본)'),
        ),
    ]
