# Generated by Django 6.0 on 2025-12-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_userprofile_can_access_scm_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='biz_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자등록번호'),
        ),
    ]
