# Generated by Django 6.0 on 2025-12-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_vendor_biz_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='delivery_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='연결 납품서 번호'),
        ),
    ]
