# Generated by ChatGPT patch on 2025-12-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_incoming_delivery_order_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='조직명(회사/협력사)')),
                ('org_type', models.CharField(choices=[('INTERNAL', '내부'), ('VENDOR', '협력사')], max_length=20, verbose_name='조직 구분')),
            ],
            options={
                'verbose_name': '조직(회사/협력사)',
                'verbose_name_plural': '조직(회사/협력사)',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('INTERNAL', '내부'), ('VENDOR', '협력사')], default='VENDOR', max_length=20, verbose_name='계정 구분'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부서/소속'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='표시 이름'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='사번'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='직책'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='orders.organization', verbose_name='소속 조직(회사/협력사)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='직급'),
        ),
    ]
