# Generated by Django 6.0 on 2026-01-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_organization_and_userprofile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', '0. 관리자 (전체 권한)'), ('STAFF', '1. 직원'), ('VENDOR', '2. 협력업체')], default='VENDOR', max_length=10, verbose_name='사용자 그룹'),
        ),
    ]
