# Generated by Django 6.0 on 2026-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', '배송중/대기'), ('RECEIVED', '입고완료(검사대기)'), ('APPROVED', '검사합격(입고확정)'), ('REJECTED', '검사불합격(반려)')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
    ]
