# Generated by Django 6.0 on 2026-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_deliveryorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ERP 발주번호'),
        ),
    ]
