# Generated by Django 6.0 on 2026-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_erp_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_order_seq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP 발주순번'),
        ),
    ]
