# Generated by Django 6.0 on 2026-01-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_erp_order_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderitem',
            name='erp_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ERP 발주번호'),
        ),
        migrations.AddField(
            model_name='deliveryorderitem',
            name='erp_order_seq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP 발주순번'),
        ),
        migrations.AddField(
            model_name='deliveryorderitem',
            name='linked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='원본 발주서'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='erp_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ERP 발주번호'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='erp_order_seq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP 발주순번'),
        ),
        migrations.AddField(
            model_name='labelprintlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='원본 발주서'),
        ),
    ]
