# Generated by Django 6.0 on 2026-01-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_deliveryorderitem_erp_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='confirmed_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='확정(양품)수량'),
        ),
    ]
