# Generated by Django 6.0 on 2026-01-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_incoming_confirmed_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='반출 대상 수량')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='반출/불량 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='판정 일시')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='반출 확인 여부')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='반출 확인 일시')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliveryorder', verbose_name='관련 납품서')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.part', verbose_name='품목')),
            ],
        ),
    ]
