# Generated by Django 6.0 on 2026-01-19 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_returnlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderitem',
            name='lot_date',
            field=models.DateField(default=datetime.date(2026, 1, 19), verbose_name='LOT 생산일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorderitem',
            name='lot_no',
            field=models.CharField(default='20000101', max_length=8, verbose_name='LOT 번호'),
            preserve_default=False,
        ),
    ]
