# Generated by Django 6.0 on 2026-01-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_deliveryorderitem_lot_date_deliveryorderitem_lot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorderitem',
            name='lot_date',
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='lot_no',
            field=models.DateField(blank=True, null=True, verbose_name='LOT 번호(생산일)'),
        ),
    ]
