# Generated by Django 6.0 on 2026-01-21 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_change_lot_to_date_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='년월')),
                ('order_qty', models.IntegerField(default=0, verbose_name='발주수량')),
                ('incoming_qty', models.IntegerField(default=0, verbose_name='입고수량')),
                ('on_time_qty', models.IntegerField(default=0, verbose_name='납기준수 수량')),
                ('delayed_qty', models.IntegerField(default=0, verbose_name='납기지연 수량')),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='납기준수율(%)')),
                ('incoming_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='입고율(%)')),
                ('avg_lead_time', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='평균 리드타임(일)')),
                ('grade', models.CharField(choices=[('A', 'A등급 (95%+)'), ('B', 'B등급 (85-95%)'), ('C', 'C등급 (85%미만)')], default='C', max_length=1, verbose_name='등급')),
                ('is_closed', models.BooleanField(default=False, verbose_name='마감 여부')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='마감 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='마감 처리자')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.vendor', verbose_name='협력사')),
            ],
            options={
                'verbose_name': '협력사 월별 실적',
                'verbose_name_plural': '협력사 월별 실적',
                'ordering': ['-year_month', 'vendor__name'],
                'unique_together': {('vendor', 'year_month')},
            },
        ),
    ]
