# Generated by Django 6.0 on 2026-01-21 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_vendor_monthly_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요 공지')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='질문일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_answers', to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_questions', to=settings.AUTH_USER_MODEL, verbose_name='질문자')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.vendor', verbose_name='협력사')),
            ],
            options={
                'verbose_name': 'Q&A',
                'verbose_name_plural': 'Q&A',
                'ordering': ['-created_at'],
            },
        ),
    ]
