# Generated by Django 6.0 on 2026-01-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_notice_qna'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='품번'),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.vendor', verbose_name='전담 업체'),
        ),
    ]
