# Generated by Django 6.0 on 2026-01-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_part_vendor_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_qms',
            field=models.BooleanField(default=False, verbose_name='QMS 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_wms',
            field=models.BooleanField(default=False, verbose_name='WMS 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_parts',
            field=models.BooleanField(default=False, verbose_name='품목 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_4m',
            field=models.BooleanField(default=False, verbose_name='4M 변경 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_inspection',
            field=models.BooleanField(default=False, verbose_name='검사 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='리포트 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_adjustment',
            field=models.BooleanField(default=False, verbose_name='재고 조정/마감'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_bom',
            field=models.BooleanField(default=False, verbose_name='BOM 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_inout',
            field=models.BooleanField(default=False, verbose_name='입출고 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_stock_view',
            field=models.BooleanField(default=False, verbose_name='재고 조회'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_scm_admin',
            field=models.BooleanField(default=False, verbose_name='통합 관리자'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_incoming',
            field=models.BooleanField(default=False, verbose_name='입고 관리'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_register_orders',
            field=models.BooleanField(default=False, verbose_name='발주 등록'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_inventory',
            field=models.BooleanField(default=False, verbose_name='과부족 조회'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_orders',
            field=models.BooleanField(default=False, verbose_name='발주 조회/승인'),
        ),
    ]
