# Generated by Django 6.0 on 2026-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_add_permission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_4m_edit',
            field=models.BooleanField(default=False, verbose_name='4M 등록/수정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_4m_view',
            field=models.BooleanField(default=False, verbose_name='4M 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_inspection_edit',
            field=models.BooleanField(default=False, verbose_name='검사 등록/판정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_inspection_view',
            field=models.BooleanField(default=False, verbose_name='검사 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_admin',
            field=models.BooleanField(default=False, verbose_name='통합 관리자'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_incoming_edit',
            field=models.BooleanField(default=False, verbose_name='입고 처리/취소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_incoming_view',
            field=models.BooleanField(default=False, verbose_name='입고 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_inventory_edit',
            field=models.BooleanField(default=False, verbose_name='소요량 등록/수정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_inventory_view',
            field=models.BooleanField(default=False, verbose_name='과부족 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_label_edit',
            field=models.BooleanField(default=False, verbose_name='납품서 등록/삭제'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_label_view',
            field=models.BooleanField(default=False, verbose_name='납품서 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_order_edit',
            field=models.BooleanField(default=False, verbose_name='발주 등록/수정/삭제'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_order_view',
            field=models.BooleanField(default=False, verbose_name='발주 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_scm_report',
            field=models.BooleanField(default=False, verbose_name='리포트 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_bom_edit',
            field=models.BooleanField(default=False, verbose_name='BOM 등록/수정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_bom_view',
            field=models.BooleanField(default=False, verbose_name='BOM 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_inout_edit',
            field=models.BooleanField(default=False, verbose_name='입출고 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_inout_view',
            field=models.BooleanField(default=False, verbose_name='입출고 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_stock_edit',
            field=models.BooleanField(default=False, verbose_name='재고 이동/조정'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_qms',
            field=models.BooleanField(default=False, verbose_name='[구]QMS 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_scm_admin',
            field=models.BooleanField(default=False, verbose_name='[구]통합 관리자'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_wms',
            field=models.BooleanField(default=False, verbose_name='[구]WMS 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_incoming',
            field=models.BooleanField(default=False, verbose_name='[구]입고 관리'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_parts',
            field=models.BooleanField(default=False, verbose_name='[구]품목 관리'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_qms_4m',
            field=models.BooleanField(default=False, verbose_name='[구]4M 관리'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_qms_inspection',
            field=models.BooleanField(default=False, verbose_name='[구]검사 관리'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_register_orders',
            field=models.BooleanField(default=False, verbose_name='[구]발주 등록'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_inventory',
            field=models.BooleanField(default=False, verbose_name='[구]과부족 조회'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_orders',
            field=models.BooleanField(default=False, verbose_name='[구]발주 조회'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='[구]리포트 조회'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_wms_adjustment',
            field=models.BooleanField(default=False, verbose_name='[구]재고 조정'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_wms_bom',
            field=models.BooleanField(default=False, verbose_name='[구]BOM 관리'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_wms_inout',
            field=models.BooleanField(default=False, verbose_name='[구]입출고 처리'),
        ),
    ]
