# Generated by Django 6.0 on 2026-01-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_link_existing_vendor_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '내부 조직', 'verbose_name_plural': '내부 조직 관리'},
        ),
    ]
