# Generated by Django 6.0 on 2026-01-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_add_qms_detailed_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='linked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='orders.order', verbose_name='원본 발주서'),
        ),
        migrations.AlterField(
            model_name='labelprintlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='orders.order', verbose_name='원본 발주서'),
        ),
        migrations.AlterField(
            model_name='labelprintlog',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='orders.part', verbose_name='품목'),
        ),
        migrations.AlterField(
            model_name='labelprintlog',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='orders.vendor', verbose_name='협력사'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qnas', to='orders.vendor', verbose_name='협력사'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_logs', to='orders.deliveryorder', verbose_name='관련 납품서'),
        ),
        migrations.AlterField(
            model_name='returnlog',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_logs', to='orders.part', verbose_name='품목'),
        ),
    ]
