# Generated by Django 6.0 on 2026-01-27 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_add_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='account_type',
            field=models.CharField(choices=[('RAW', '원재료'), ('PRODUCT', '상품'), ('FINISHED', '제품')], default='RAW', max_length=10, verbose_name='계정구분'),
        ),
        migrations.CreateModel(
            name='InventoryUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('INVENTORY', '기초재고'), ('PART_MASTER', '품목마스터'), ('DEMAND', '소요량')], max_length=20, verbose_name='업로드 유형')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('part_no', models.CharField(max_length=50, verbose_name='품번')),
                ('part_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='품명')),
                ('row_data', models.TextField(blank=True, null=True, verbose_name='원본 행 데이터')),
                ('error_reason', models.CharField(max_length=255, verbose_name='실패 사유')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '업로드 실패 로그',
                'verbose_name_plural': '업로드 실패 로그',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
