# Generated by Django 6.0 on 2026-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='weight_qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=17, verbose_name='단위중량'),
        ),
        migrations.AddField(
            model_name='part',
            name='weight_unit',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='중량단위'),
        ),
    ]
