# Generated by Django 6.0 on 2026-03-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_add_weight_to_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_doc_edit',
            field=models.BooleanField(default=False, verbose_name='품질문서 등록/수정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_doc_view',
            field=models.BooleanField(default=False, verbose_name='품질문서 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_gauge_edit',
            field=models.BooleanField(default=False, verbose_name='계측기 등록/수정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_gauge_view',
            field=models.BooleanField(default=False, verbose_name='계측기 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_voc_edit',
            field=models.BooleanField(default=False, verbose_name='VOC 등록/처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_qms_voc_view',
            field=models.BooleanField(default=False, verbose_name='VOC 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_field_edit',
            field=models.BooleanField(default=False, verbose_name='현장 지원 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_field_view',
            field=models.BooleanField(default=False, verbose_name='현장 지원 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_label_edit',
            field=models.BooleanField(default=False, verbose_name='입고라벨 발행/취소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_label_view',
            field=models.BooleanField(default=False, verbose_name='입고라벨 조회'),
        ),
        migrations.CreateModel(
            name='RoleDefaultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', '0. 관리자 (전체 권한)'), ('STAFF', '1. 직원'), ('VENDOR', '2. 협력업체')], max_length=10, verbose_name='역할')),
                ('permission_field', models.CharField(max_length=50, verbose_name='권한 필드명')),
            ],
            options={
                'verbose_name': '역할별 기본 권한',
                'verbose_name_plural': '역할별 기본 권한',
                'unique_together': {('role', 'permission_field')},
            },
        ),
    ]
