# Generated by Django 6.0 on 2026-03-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_seed_role_default_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_qms_voc_edit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_qms_voc_view',
        ),
    ]
