# Generated by Django 6.0 on 2026-04-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_remove_qms_voc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자명'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자 연락처'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
    ]
