# Generated by Django 6.0 on 2026-06-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_add_vendor_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_bom_calc',
            field=models.BooleanField(default=False, verbose_name='소요량 계산'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_bom_list',
            field=models.BooleanField(default=False, verbose_name='BOM 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_bom_upload',
            field=models.BooleanField(default=False, verbose_name='BOM 업로드'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_erp_sync',
            field=models.BooleanField(default=False, verbose_name='기초재고 동기화'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_incoming_history',
            field=models.BooleanField(default=False, verbose_name='입고 내역 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_incoming_label',
            field=models.BooleanField(default=False, verbose_name='입고라벨 발행'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_incoming_process',
            field=models.BooleanField(default=False, verbose_name='입고 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_lot_allocation',
            field=models.BooleanField(default=False, verbose_name='LOT 별도 적용'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_outbound',
            field=models.BooleanField(default=False, verbose_name='생산 자재 불출'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_outgoing_history',
            field=models.BooleanField(default=False, verbose_name='출고 내역 조회'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_outgoing_process',
            field=models.BooleanField(default=False, verbose_name='출고 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_stock_list',
            field=models.BooleanField(default=False, verbose_name='자재 재고 현황'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_stock_return',
            field=models.BooleanField(default=False, verbose_name='불량 반품 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_stock_transfer',
            field=models.BooleanField(default=False, verbose_name='재고 이동 처리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_storage_expiry',
            field=models.BooleanField(default=False, verbose_name='유효기간 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_storage_layout',
            field=models.BooleanField(default=False, verbose_name='창고 레이아웃'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_storage_rack',
            field=models.BooleanField(default=False, verbose_name='랙 위치 관리'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_storage_setting',
            field=models.BooleanField(default=False, verbose_name='품목 설정'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_transaction_history',
            field=models.BooleanField(default=False, verbose_name='기간별 수불 대장'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_transfer_history',
            field=models.BooleanField(default=False, verbose_name='재고 이동 현황'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_transfer_request',
            field=models.BooleanField(default=False, verbose_name='재료 이동 요청'),
        ),
    ]
