# Generated by Django 6.0 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_wms_submenu_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_wms_purchase_approve',
            field=models.BooleanField(default=False, verbose_name='발주신청 승인'),
        ),
    ]
