# Generated by Django 6.0 on 2026-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_userprofile_can_wms_purchase_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', '배송중/대기'), ('RECEIVED', '입고완료(검사대기)'), ('APPROVED', '검사합격(입고확정)'), ('REJECTED', '검사불합격(반려)'), ('CANCELLED', '취소됨')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
    ]
